/**
 * The owner's recovery key, with no Node dependency.
 *
 * Kept apart from `access.ts` so a browser can import it: the owner derives
 * their key in the page, from their own wallet's signature, and the private
 * half never leaves it.
 */
import { keccak256, type Hex } from 'viem'
import { privateKeyToAccount } from 'viem/accounts'

/**
 * The owner's key, derived from a wallet signature.
 *
 * The content keys are generated by whatever app writes the namespace. If that
 * app's data is deleted, the keys go with it — and without them even the owner
 * cannot read their own memory. So every namespace also carries a grant sealed
 * to a key the owner can always re-create: sign a fixed message with their
 * wallet, hash the signature, use it as a private key. Deterministic, because
 * wallet signatures are (RFC 6979), and never sent anywhere — only the public
 * half is.
 */
export const OWNER_KEY_MESSAGE = (name: string) =>
  `knowledge.eth owner key\n\nThis signature derives the key that lets you read your own memory from the network, from any app, even if the one you use today disappears.\n\nIt authorises no transaction and costs nothing.\n\nName: ${name}`

export function ownerKeyFromSignature(signature: Hex): { privateKey: Hex; pubkey: Hex } {
  // A 32-byte hash falls outside the curve order with probability ~2^-128.
  // Re-hashing keeps the derivation deterministic in that case rather than
  // throwing for one owner in a few undecillion.
  let privateKey = keccak256(signature)
  for (let i = 0; i < 4; i++) {
    try { return { privateKey, pubkey: privateKeyToAccount(privateKey).publicKey } }
    catch { privateKey = keccak256(privateKey) }
  }
  throw new Error('could not derive an owner key from this signature')
}
