import Link from 'next/link'
import { Diagram, Footer, Hero, Section } from '@/components/Guide'
import { Arrow } from '@/components/Arrow'

export const metadata = { title: 'Use cases' }

const CASES = [
  { title: 'Treasury Agent', ns: 'treasury.kestrel.eth', kind: 'organisation · private', who: 'Crypto-native companies, DAOs and funds that hold a treasury on chain', why: 'A treasury recommendation is only as good as the policy and the facts behind it, and both change. At Kestrel the policy is a reviewed namespace: “keep at least 18 months of operating runway in USDC”, “no single DeFi protocol may hold more than 15% of treasury assets”, “payroll needs ~$420k in USDC on the operating Safe by the 1st”. Each claim cites the document it came from (Treasury policy v3) and carries the CFO’s review. When the agent says “rebalance”, anyone can see which policy version and which balances it read.', how: 'kestrel.eth owns the namespace; cfo.kestrel.eth reviews; treasury-agent.eth may propose. The agent monitors balances and liquidity, reads the policy, and proposes a recommendation — it does not move funds. Acting stays a separate, human-approved transaction, which is the line this product draws everywhere: it learns, it never acts.', status: 'Partly live: the Ethereum wallet source reads holdings and the protocols a treasury uses. The recommending agent is not built yet', href: '/roles/owner' },
  { title: 'On-Chain Monitoring Agent', ns: 'watch.kestrel.eth', kind: 'organisation · private', who: 'Security and finance teams watching wallets, contracts and transactions', why: 'Unusual only means something against a written-down normal. “The payroll Safe pays contributors on the 1st of each month; outflows on other days are unusual.” “The treasury multisig is 3-of-5; a signer change is always worth an alert.” “The vesting contract releases to known recipients only.” Kept as reviewed claims, normal has an owner and a version, so an alert can say which rule it broke and who wrote that rule.', how: 'watch-agent.eth reads the chain against the current version and surfaces what does not fit. When normal changes — a new signer, a new payroll date — the agent proposes a supersession and cfo.kestrel.eth lands it; the old rule stays in history.', status: 'Model ready: the namespace, review and supersession are live. The alerting agent is not built yet', href: '/for-agents' },
  { title: 'Portfolio Intelligence Agent', ns: 'portfolio.kestrel.eth', kind: 'organisation · private', who: 'Anyone who wants to ask about holdings, transactions and yield in plain language', why: 'Questions like “what did we earn in yield last quarter?” or “when did we first stake?” need a history, not a snapshot. Positions become versioned claims with their sources — tx hash, protocol, date: “Kestrel staked 200 ETH through Lido in March 2026.” Context a block explorer cannot give is a claim too: “The USDC in Aave is the runway reserve, not a trading position.” Any assistant the owner allows can answer from it, and it survives switching portfolio apps.', how: 'The Ethereum wallet source reads an address through Blockscout’s public API — no key, no cost — and writes what it holds and which protocols it uses; portfolio-agent.eth adds context. Supersession records a position that changed rather than overwriting it. An assistant answers with knowledge_search and cites each claim it used; “why do you think that?” is knowledge_why.', status: 'Live for Ethereum: connect a wallet and holdings and protocols land in portfolio.<your name>.eth. Yield and full transaction history are next', href: '/app' },
  { title: 'Research communities', ns: 'cancer-research.eth → trials.cancer-research.eth', kind: 'public', who: 'Researchers, labs and review boards; every agent that answers questions about the field', why: 'Provenance and review are the product. “Olaparib, a PARP inhibitor, is approved for BRCA-mutated advanced ovarian cancer” is worth citing only with its source (the FDA approval, December 2014), who proposed it and who checked it. A claim that changed because a source was found wrong is a supersession with the old value kept.', how: 'The owner registers the root and hands children — trials, immunotherapy — to their own owners and reviewers. Anyone proposes with papers, trial registry entries or regulatory approvals as sources; automated review flags duplicates, contradictions and missing sources; oncology-review.eth lands. Agents read by name.', status: 'Model ready; needs a community', href: '/roles/contributor' },
  { title: 'Team coding conventions', ns: 'conventions.acme.eth', kind: 'organisation', who: 'Engineering teams using several AI coding agents', why: '“We use pnpm, not npm” is not memory. It is a team convention with an owner, a reason and a date it changed — authored, contested, versioned. Today it lives in one vendor’s store for whichever teammate happened to say it. As a namespace every agent on the team reads the same one, and a change is a proposal a maintainer lands.', how: 'Owner registers conventions.<org>.eth (kind: organisation, approvals ≥ 1). An adapter tells each agent to knowledge_search before answering and knowledge_propose after learning a convention. Reviewers land; push publishes on an interval.', status: 'Live: conventions.acme.eth · adapters for Claude Code and Cursor', href: '/k/conventions.acme.eth' },
  { title: 'Composed personal + shared knowledge', ns: 'food.rishikesh.eth + japan.travel.eth + tokyo.food.eth', kind: 'personal + public', who: 'Assistant builders; end users who want their AI to not start from zero', why: 'Three owners, one answer, no data ever copied into the assistant’s vendor. The personal namespace is private and encrypted; the shared ones are public and reviewed.', how: 'The agent resolves each name, reads the current version, composes. It could not modify any of them; it could propose.', status: 'Demo: /demo/travel (scripted agent; real retrieval and provenance)', href: '/demo/travel' },
  { title: 'Organisation knowledge', ns: 'company.eth', kind: 'organisation', who: 'Companies using several AI vendors', why: 'Portable across the vendors the company uses; revocable by re-keying; auditable by version. Wrong answers have consequences, so the audit trail is the point.', how: 'Private namespace, internal reviewers, interval publishing. Agents on any vendor read the same version.', status: 'Model ready', href: '/roles/owner' },
  { title: 'Agent-maintained namespaces', ns: 'research.ai.eth', kind: 'public', who: 'Teams running autonomous research or monitoring agents', why: 'Agents propose; humans approve; every agent claim is attributed and reviewable. An agent is a source like any other.', how: 'knowledge_propose from the agent; automated findings first; a human reviewer lands.', status: 'Live: MCP knowledge_propose', href: '/for-agents' },
]

export default function UseCases() {
  return (
    <>
      <Hero kicker="Use cases" title="Where a name, a version and a review earn their keep." sub="The strongest cases are the ones where an agent acts on knowledge someone else owns and reviews. Agents in production first, then the communities and teams they read from — and honest about which parts are live." />
      <main className="w-full px-5 sm:px-8 lg:px-10">
        <Section title="The test for any new case" intro="Would a second party want to know where this came from? If yes, it is knowledge and belongs here. If no, it is memory — still supported, as a private namespace with no review gate.">
          <Diagram>{`memory     one principal · byproduct of interaction · goes stale         → private namespace, approvals: 0
knowledge  authored · has a truth condition · read by others            → sources, reviewer, version`}</Diagram>
        </Section>
        <Section title={`${CASES.length} cases`}>
          <div className="space-y-4">
            {CASES.map((c, i) => (
              <div key={c.title} className="rounded-2xl border border-line bg-surface p-5">
                <div className="flex flex-wrap items-baseline gap-3"><span className="font-mono text-[13.5px] text-dim">{i + 1}</span><h3 className="text-lg font-semibold">{c.title}</h3><code className="font-mono text-[13.5px] text-accent">{c.ns}</code><span className="rounded bg-raised px-2 py-0.5 text-[12.5px] text-dim">{c.kind}</span></div>
                <div className="mt-3 grid gap-4 md:grid-cols-3 text-[14.5px] leading-relaxed">
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">Who</p><p className="mt-1 text-ink/85">{c.who}</p><p className="mt-3 text-[12.5px] font-medium uppercase tracking-wider text-dim">Why not a database</p><p className="mt-1 text-ink/85">{c.why}</p></div>
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">How it works here</p><p className="mt-1 text-ink/85">{c.how}</p></div>
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">Status</p><p className="mt-1 text-ink/85">{c.status}</p><Link href={c.href} className="mt-3 inline-block text-[15px] text-ink underline underline-offset-4 hover:opacity-70">open <Arrow /></Link></div>
                </div>
              </div>
            ))}
          </div>
        </Section>
        <Footer />
      </main>
    </>
  )
}
