import Link from 'next/link'
import { Diagram, Footer, Hero, Section } from '@/components/Guide'
import { Arrow } from '@/components/Arrow'

export const metadata = { title: 'Use cases' }

const CASES = [
  { title: 'Team coding conventions', ns: 'conventions.acme.eth', kind: 'organisation', who: 'Engineering teams using several AI coding agents', why: '“We use pnpm, not npm” is not memory. It is a team convention with an owner, a reason and a date it changed — authored, contested, versioned. Today it lives in one vendor’s store for whichever teammate happened to say it. As a namespace every agent on the team reads the same one, and a change is a proposal a maintainer lands.', how: 'Owner registers conventions.<org>.eth (kind: organisation, approvals ≥ 1). An adapter tells each agent to knowledge_search before answering and knowledge_propose after learning a convention. Reviewers land; push publishes on an interval.', status: 'Live: conventions.recalltest.eth · adapters for Claude Code and Cursor', href: '/k/conventions.recalltest.eth' },
  { title: 'Public reference knowledge', ns: 'history.eth → india.history.eth', kind: 'public', who: 'Curators, experts, communities; every agent that answers questions about the subject', why: 'Ownership per branch of the tree; anyone proposes, named reviewers approve; any agent cites the version. A wiki with a review queue, an owner per volume, and a name any application resolves.', how: 'Owner registers the root, hands children to other owners, sets reviewers. Contributors propose with sources; automated review flags duplicates, contradictions and missing sources; reviewers land. Agents read by name.', status: 'Live: worldhistory.eth v2 · india.worldhistory.eth v1', href: '/k/worldhistory.eth' },
  { title: 'Source integrations', ns: 'wikipedia.history.eth · weather.india.eth', kind: 'public', who: 'Publishers, data owners, API providers', why: 'A source keeps its identity on every claim across every consumer. An encyclopedia, a news feed or a government dataset becomes discoverable and citable by AI without each application scraping it.', how: 'The source (or its owner) runs an importer against the same propose path. Wikipedia’s is live: one article → sentences → claims with source and excerpt → one proposal.', status: 'Live: Wikipedia importer (proposal #2 on worldhistory.eth) · catalogue of further sources', href: '/sources' },
  { title: 'Composed personal + shared knowledge', ns: 'food.rishikesh.eth + japan.travel.eth + tokyo.food.eth', kind: 'personal + public', who: 'Assistant builders; end users who want their AI to not start from zero', why: 'Three owners, one answer, no data ever copied into the assistant’s vendor. The personal namespace is private and encrypted; the shared ones are public and reviewed.', how: 'The agent resolves each name, reads the current version, composes. It could not modify any of them; it could propose.', status: 'Demo: /demo/travel (scripted agent; real retrieval and provenance)', href: '/demo/travel' },
  { title: 'Research communities', ns: 'cancer-research.eth', kind: 'public or organisation', who: 'Researchers, labs, journals', why: 'Provenance and review are the product. Contradictions are the interesting events; a claim that changed because a source was found wrong is a supersession with the old value kept.', how: 'Reviewers are named experts; approvals ≥ 2; signed approvals on. Findings queue as the triage surface.', status: 'Model ready; needs a community', href: '/roles/reviewer' },
  { title: 'Organisation knowledge', ns: 'company.eth', kind: 'organisation', who: 'Companies using several AI vendors', why: 'Portable across the vendors the company uses; revocable by re-keying; auditable by version. Wrong answers have consequences, so the audit trail is the point.', how: 'Private namespace, internal reviewers, interval publishing. Agents on any vendor read the same version.', status: 'Model ready', href: '/roles/owner' },
  { title: 'AI treasury agent', ns: 'treasury.acme.eth · policy.treasury.acme.eth', kind: 'organisation', who: 'DAOs, crypto-native companies and funds managing on-chain assets', why: 'A treasury recommendation is only as good as the policy and the facts behind it, and both change. Here the policy — "keep 6 months of runway in stables", "never hold more than 20% in one protocol" — is a reviewed namespace with an owner and a history, and every balance or liquidity observation the agent relies on is a claim citing the chain it was read from. When the agent says "rebalance", anyone can see which policy version and which balances it read.', how: 'The policy lives in a namespace with approvals ≥ 2 (the treasury committee). A reader observes the treasury addresses — balances, positions, upcoming obligations — and writes claims citing block and transaction. The agent reads both and proposes a recommendation; it does not move funds. Acting stays a separate, human-approved transaction, which is the line this product draws everywhere: it learns, it never acts.', status: 'Partly live: the Ethereum wallet source reads holdings and the protocols a treasury uses. The policy namespace and the recommending agent are not built yet', href: '/roles/reviewer' },
  { title: 'Portfolio intelligence agent', ns: 'portfolio.rishikesh.eth', kind: 'personal', who: 'Anyone holding assets across wallets, exchanges and protocols who wants to ask about them in plain language', why: 'Questions like "what did I earn in yield last quarter?" or "when did I first buy this?" need a history, not a snapshot, and they need it to be the person\'s, not an app\'s. As a private namespace, holdings, transactions and yield become versioned claims with their sources — tx hash, protocol, date — that any assistant the person allows can answer from, and that survive switching portfolio apps.', how: 'Private namespace, approvals: 0. The Ethereum wallet source reads the address you signed in with through Blockscout\'s public API — no key, no cost — and writes what you hold and which protocols you use, never an amount (exchange exports, where a CSV is the only door, are next); supersession records a position that changed rather than overwriting it. An assistant answers with knowledge_search and cites each claim it used; "why do you think that?" is knowledge_why.', status: 'Live for Ethereum: connect your wallet and holdings and protocols land in portfolio.<your name>.eth. Yield and full transaction history are next', href: '/app' },
  { title: 'Agent-maintained namespaces', ns: 'research.ai.eth', kind: 'public', who: 'Teams running autonomous research or monitoring agents', why: 'Agents propose; humans approve; every agent claim is attributed and reviewable. An agent is a source like any other.', how: 'knowledge_propose from the agent; automated findings first; a human reviewer lands.', status: 'Live: MCP knowledge_propose', href: '/for-agents' },
]

export default function UseCases() {
  return (
    <>
      <Hero kicker="Use cases" title="Where a name, a version and a review earn their keep." sub="The strongest cases are the ones where knowledge is shared between parties who do not share a database. Ranked by how much the identity layer adds — and honest about which are live." />
      <main className="w-full px-5 sm:px-8 lg:px-10">
        <Section title="The test for any new case" intro="Would a second party want to know where this came from? If yes, it is knowledge and belongs here. If no, it is memory — still supported, as a private namespace with no review gate.">
          <Diagram>{`memory     one principal · byproduct of interaction · goes stale         → private namespace, approvals: 0
knowledge  authored · has a truth condition · read by others            → sources, reviewer, version`}</Diagram>
        </Section>
        <Section title={`${CASES.length} cases`}>
          <div className="space-y-4">
            {CASES.map((c, i) => (
              <div key={c.title} className="rounded-2xl border border-line bg-surface p-5">
                <div className="flex flex-wrap items-baseline gap-3"><span className="font-mono text-[13.5px] text-dim">{i + 1}</span><h3 className="text-lg font-semibold">{c.title}</h3><code className="font-mono text-[13.5px] text-accent">{c.ns}</code><span className="rounded bg-raised px-2 py-0.5 text-[12.5px] text-dim">{c.kind}</span></div>
                <div className="mt-3 grid gap-4 md:grid-cols-3 text-[14.5px] leading-relaxed">
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">Who</p><p className="mt-1 text-ink/85">{c.who}</p><p className="mt-3 text-[12.5px] font-medium uppercase tracking-wider text-dim">Why not a database</p><p className="mt-1 text-ink/85">{c.why}</p></div>
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">How it works here</p><p className="mt-1 text-ink/85">{c.how}</p></div>
                  <div><p className="text-[12.5px] font-medium uppercase tracking-wider text-dim">Status</p><p className="mt-1 text-ink/85">{c.status}</p><Link href={c.href} className="mt-3 inline-block text-[15px] text-ink underline underline-offset-4 hover:opacity-70">open <Arrow /></Link></div>
                </div>
              </div>
            ))}
          </div>
        </Section>
        <Footer />
      </main>
    </>
  )
}
